<a href="https://colab.research.google.com/github/hiep273/ML_Notebooks/blob/main/linearregression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Áp dụng mô hình ANN vào bài toán hồi quy


## cai dat thu vien


In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.19.0'

##chuan bi du lieu


In [2]:
dataset=pd.read_excel("new_dataset.xlsx",sheet_name='Sheet1')
print(dataset)
X=dataset.iloc[:, :-1].values
Y=dataset.iloc[:,-1].values

         AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]


In [ ]:
print(X)


[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(Y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### chia du lieu train va test

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

##buiding ANN


In [6]:
# tao mot doi tuowg
ann= tf.keras.models.Sequential()


###first layer


In [7]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

###seconds layer


In [8]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))


###output layer

In [9]:
ann.add(tf.keras.layers.Dense(units=1))

##training ANN


###bien dich mo hinh


In [10]:
ann.compile(optimizer='adam',loss='mean_squared_error')

###training ANN


In [11]:
ann.fit(X_train,Y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 22754.9941
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 378.5657
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.1470
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 342.7469
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 317.1107
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 288.8300
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 258.1464
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 229.3649
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 195.6140
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 161.6576
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 133.6711
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 110.0395
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 67.1984
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55.1303
Epoch 15/100
24

###du doan ket qua


In [13]:
y_pred=ann.predict(X_test)
np.set_printoptions(precision=2)# lm tron den so thap phan thu 2
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))




60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[431.42 431.23]
 [462.49 460.01]
 [466.02 461.14]
 ...
 [473.19 473.26]
 [440.07 438.  ]
 [459.23 463.28]]
